# Generated by Django 4.2.13 on 2024-06-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='photo',
        ),
        migrations.AddField(
            model_name='equipment',
            name='idNumber',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipment',
            name='image',
            field=models.ImageField(default=None, upload_to='uploads/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipment',
            name='local',
            field=models.TextField(),
        ),
    ]
