# Generated by Django 4.2.13 on 2024-06-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_equipment_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='idNumber',
            field=models.IntegerField(default=None),
        ),
    ]
